AgroSup.WebApp/ViewModels/AdminPanel/PlantViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AgroSup.WebApp.ViewModels.AdminPanel
{
    public class PlantViewModel
    {
        public Guid Id { get; set; }
        [Required(ErrorMessage = "To pole jest wymagane")]
        [DisplayName("Nazwa")]
        public string Name { get; set; }
        [Required(ErrorMessage = "To pole jest wymagane")]
        [DisplayName("Współczynnik EFA")]
        public int EfaNitrogenRate { get; set; }
        public bool Delete { get; set; }
    }
}

AgroSup.WebApp/ViewModels/AdminPanel/Plants/PlantViewModel.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace AgroSup.WebApp.ViewModels.AdminPanel.Plants
{
    public class PlantViewModel
    {
        public Guid Id { get; set; }
        [Required(ErrorMessage = "Nazwa jest wymagana")]
        [DisplayName("Nazwa")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Musisz podać współczynnik")]
        [Range(0,2,ErrorMessage ="Współczynnik musi być z przedziału [0,2]")]
        [DisplayName("Współczynnik EFA")]
        public int EfaNitrogenRate { get; set; }
        public bool Delete { get; set; }
    }
}

AgroSup.WebApp/ViewModels/Plants/PlantViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AgroSup.WebApp.ViewModels.Plants
{
    public class PlantViewModel
    {
        public IList<string> SelectedPlants { get; set; } = new List<string>();
        public IList<SelectListItem> AvailablePlants { get; set; } = new List<SelectListItem>();
    }
}

AgroSup.WebApp/Controllers/PlantsController.cs
using AgroSup.Core.Domain;
using AgroSup.Core.Repositories;
using AgroSup.WebApp.ViewModels.Plants;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AgroSup.WebApp.Controllers
{
    public class PlantsController : BaseController
    {
        private readonly IPlantRepository _plantRepository;

        public PlantsController(
            IPlantRepository plantRepository,
            UserManager<User> userManager,
            IUserRepository userRepository
            ) : base(userManager, userRepository)
        {
            _plantRepository = plantRepository;

        }

        public async Task<IActionResult> ChoosePlants()
        {
            var userPlants = LoggedUser.ChoosedPlants;

            var model = new PlantViewModel()
            {
                AvailablePlants = await GetAvailablePlants(),
                SelectedPlants = userPlants.Select(x => x.Plant.Id.ToString()).ToList(),
            };

            return View(model);
        }
        [HttpPost]
        public async Task AssignPlant(Guid id)
        {
            var plant = await _plantRepository.GetById(id);
            if(plant != null)
            {
                LoggedUser.AddPlantToChoosed(plant);
            await UpdateLoggedUser();
            }
        }
        [HttpPost]
        public async Task UnAssignPlant(Guid id)
        {
            var plant = await _plantRepository.GetById(id);
            if (plant != null)
            {
                LoggedUser.RemovePlantFromChoosed(plant);
                await UpdateLoggedUser();
            }
        }

        // Methods
        private async Task<IList<SelectListItem>> GetAvailablePlants()
        {
            var plants = await _plantRepository.GetAll();
            return plants.Select(x => new SelectListItem()
            {
                Text = x.Name,
                Value = x.Id.ToString(),
            }).ToList();
        }

    }
}

AgroSup.WebApp/Views/Plants/ChoosePlants.cshtml
@model AgroSup.WebApp.ViewModels.Plants.PlantViewModel

@{
    ViewData["Title"] = "Wybierz rośliny";
    ViewData["Header"] = "Wybierz rośliny, które uprawiasz";
    ViewData["ActivePage"] = ManageMenu.ChoosePlants;
    var message = @TempData["message"];
}

<!--- Content -->
<div class="row">
    <partial name="_DataMenuPartial" />
    <div class="col-md-10">
        <div class="container-md mx-4">
            <p class="text-center" id="headerTitle">@ViewData["Header"]</p>
            <hr />
            @if (message != null)
            {
                <partial name="_StatusMessage" model="message.ToString()" />
            }
                <table id="dtDynamicVerticalScrollExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th class="th-sm">Roślina</th>
                            <th class="th-sm">Uprawiam</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.AvailablePlants)
                        {
                            var selected = @Model.SelectedPlants.Contains(item.Value) == true ? 1 : 0;
                            <tr>
                                <td>@item.Text</td>
                                <td data-order=@selected>
                                    <div class="custom-control custom-switch">
                                        <input type="checkbox" class="custom-control-input" name="SelectedPlants" id="@item.Value" value="@item.Value" @if (Model.SelectedPlants.Contains(item.Value)) { <text> checked data-order=1 </text> } } />
                                        <label class="custom-control-label" for="@item.Value" onclick="choosePlant.call(this)">Kliknij tutaj</label>
                                    </div>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
        </div>
    </div>
</div>
<!--- End content -->

@section Scripts {
    <script type="text/javascript" src="~/md/js/addons/datatables.min.js"></script>

    <script>
        function choosePlant() {
            var input = $(this).siblings('input[name=SelectedPlants]');
            var id = input.val();
            var assign = input.prop('checked') == false ? true : false;
            if (assign) {
                $.ajax({
                    async: true,
                    data: "Id=" + id,
                    type: "POST",
                    url: '@Url.Action("AssignPlant", "Plants")',
                });
            } else {
                $.ajax({
                    async: true,
                    data: "Id=" + id,
                    type: "POST",
                    url: '@Url.Action("UnAssignPlant", "Plants")',
                });
            }

        }
        $(document).ready(function () {
            $('#dtDynamicVerticalScrollExample').DataTable({
                "scrollY": "50vh",
                "scrollCollapse": true,
                "bInfo": false,
                "iDisplayLength": 50,
                "oLanguage": {
                    "sSearch": "Wyszukaj roślinę:",
                    "sLengthMenu": "Wyświetl _MENU_ roślin",
                    "sInfoEmpty": "Nie znaleziono żadnych roślin",
                    "sZeroRecords": "Nie znaleziono roślin o podanych wymaganiach",
                    "oPaginate": {
                        "sNext": "Następna",
                        "sPrevious": "Poprzednia",
                    },
                }
            });
            $('.dataTables_length').addClass('bs-select');
        });
    </script>
}


@section Styles {
    <link href="~/md/css/addons/datatables.min.css" rel="stylesheet">
    <style>
        table.dataTable thead .sorting:after,
        table.dataTable thead .sorting:before,
        table.dataTable thead .sorting_asc:after,
        table.dataTable thead .sorting_asc:before,
        table.dataTable thead .sorting_asc_disabled:after,
        table.dataTable thead .sorting_asc_disabled:before,
        table.dataTable thead .sorting_desc:after,
        table.dataTable thead .sorting_desc:before,
        table.dataTable thead .sorting_desc_disabled:after,
        table.dataTable thead .sorting_desc_disabled:before {
            bottom: .5em;
        }
    </style>
}