AgroSup.WebApp/ViewModels/Operators/OperatorViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AgroSup.WebApp.ViewModels.Operators
{
    public class OperatorViewModel
    {
        public Guid Id { get; set; }
        [DisplayName("Imię")]
        [Required(ErrorMessage ="To pole jest wymagane")]
        [RegularExpression(@"^[a-zA-ZąćęłńóśżźĄĆĘŁŃÓŚŻŹ]{2,20}$",ErrorMessage ="Niepoprawne imię")]
        public string FirstName { get; set; }
        [RegularExpression(@"^[a-zA-ZąćęłńóśżźĄĆĘŁŃÓŚŻŹ]{2,40}$", ErrorMessage = "Niepoprawne nazwisko")]
        [DisplayName("Nazwisko")]
        public string LastName { get; set; }
        [RegularExpression(@"^[0-9]{11}$", ErrorMessage = "Niepoprawny numer")]
        [DisplayName("Numer identyfikacyjny ARIMR")]
        public string ArimrNumber { get; set; }
    }
}

AgroSup.WebApp/Controllers/OperatorsController.cs
using AgroSup.Core.Domain;
using AgroSup.Core.Repositories;
using AgroSup.WebApp.ViewModels.Operators;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace AgroSup.WebApp.Controllers
{
    public class OperatorsController : BaseController
    {
        private readonly IOperatorRepository _operatorRepository;

        public OperatorsController(
            UserManager<User> userManager,
            IUserRepository userRepository,
            IOperatorRepository operatorRepository
            ) : base(userManager, userRepository)
        {
            _operatorRepository = operatorRepository;
        }

        public async Task<IActionResult> Index()
        {
            if (ManagedYearPlan == null)
            {
                return ActionIfNotChoosedManagedYearPlan();
            }

            var operators = await _operatorRepository.GetByYearPlan(ManagedYearPlan);
            var model = operators.Select(x => new OperatorViewModel()
            {
                Id = x.Id,
                FirstName = x.FirstName,
                LastName = x.LastName,
                ArimrNumber = x.ArimrNumber
            });
            return View(model);
        }
        [HttpGet]
        public IActionResult Create()
        {
            if (ManagedYearPlan == null)
            {
                return ActionIfNotChoosedManagedYearPlan();
            }

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(OperatorViewModel model)
        {
            if (ManagedYearPlan == null)
            {
                return ActionIfNotChoosedManagedYearPlan();
            }

            if (!ModelState.IsValid)
            {
                return View();
            }

            Operator @operator = new Operator()
            {
                FirstName = model.FirstName,
                LastName = model.LastName,
                ArimrNumber = model.ArimrNumber,
                YearPlan = ManagedYearPlan,
            };
            await _operatorRepository.Add(@operator);
            TempData["message"] = "Nowa osoba została dodana";
            ModelState.Clear();
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Edit(Guid id)
        {
            if (ManagedYearPlan == null)
            {
                return ActionIfNotChoosedManagedYearPlan();
            }

            if (id == null)
            {
                return NotFound();
            }
            var @operator = await _operatorRepository.GetById(id);

            if (@operator == null)
            {
                return NotFound();
            }

            var model = new OperatorViewModel()
            {
                Id = @operator.Id,
                FirstName = @operator.FirstName,
                LastName = @operator.LastName,
                ArimrNumber = @operator.ArimrNumber
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(OperatorViewModel model)
        {
            if (ManagedYearPlan == null)
            {
                return ActionIfNotChoosedManagedYearPlan();
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var @operator = await _operatorRepository.GetById(model.Id);
            @operator.FirstName = model.FirstName;
            @operator.LastName = model.LastName;
            @operator.ArimrNumber = model.ArimrNumber;
            await _operatorRepository.Update(@operator);
            TempData["message"] = "Zmiany zostały zapisane pomyślnie";
            return View(model);
        }
        public async Task<IActionResult> Delete(Guid id)
        {
            if (ManagedYearPlan == null)
            {
                return ActionIfNotChoosedManagedYearPlan();
            }

            var @operator = await _operatorRepository.GetById(id);
            await _operatorRepository.Delete(@operator);
            return RedirectToAction("Index");
        }
    }
}

AgroSup.WebApp/Views/Operators/Create.cshtml
@model AgroSup.WebApp.ViewModels.Operators.OperatorViewModel

@{
    ViewData["Title"] = "Osoba";
    ViewData["Header"] = "Dodaj dane osoby zarejestrowanej w systemie ARiMR";
    ViewData["ActivePage"] = ManageMenu.OperatorAdd;
    var message = @TempData["message"];
}

<!--- Content -->
<div class="row">
    <partial name="_DataMenuPartial" />
    <div class="col-md-10">
        <div class="container-md mx-4">
            <p class="text-center" id="headerTitle">@ViewData["Header"]</p>
            <hr />
            @if (message != null)
            {
                <partial name="_StatusMessage" model="message.ToString()" />
            }
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="FirstName" class="control-label"></label>
                    <input asp-for="FirstName" class="form-control" />
                    <small id="firstNameHelp" class="form-text text-muted">Podaj imię osoby, która zarządza gospodarstwem.</small>
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LastName" class="control-label"></label>
                    <input asp-for="LastName" class="form-control" />
                    <small id="surnameHelp" class="form-text text-muted">Podaj nazwiso osoby, która zarządza gospodarstwem.</small>
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ArimrNumber" class="control-label"></label>
                    <input asp-for="ArimrNumber" class="form-control" />
                    <span asp-validation-for="ArimrNumber" class="text-danger"></span>
                    <small id="arimrNumberHelp" class="form-text text-muted">Podaj numer otrzymany od ARIMR. (opcjonalnie) </small>
                </div>
                <div class="form-group">
                    <input type="submit" value="Dodaj" class="btn btn-primary" />
                    @Html.ActionLink("Powrót", "Index", new { }, new { @class = "btn btn-info" })
                </div>
            </form>
        </div>
    </div>
</div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

AgroSup.WebApp/Views/Operators/Edit.cshtml
@model AgroSup.WebApp.ViewModels.Operators.OperatorViewModel

@{
    ViewData["Title"] = "Osoba";
    ViewData["Header"] = "Edytuj dane osoby";
    ViewData["ActivePage"] = ManageMenu.OperatorAdd;
    var message = @TempData["message"];
}

<!--- Content -->
<div class="row">
    <partial name="_DataMenuPartial" />
    <div class="col-md-10">
        <div class="container-md mx-4">
            <p id="headerTitle">@ViewData["Header"]</p>
            <hr />
            @if (message != null)
            {
                <partial name="_StatusMessage" model="message.ToString()" />
            }
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <label asp-for="FirstName" class="control-label"></label>
                    <input asp-for="FirstName" class="form-control" />
                    <small id="firstNameHelp" class="form-text text-muted">Podaj imię osoby, która zarządza gospodarstwem.</small>
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LastName" class="control-label"></label>
                    <input asp-for="LastName" class="form-control" />
                    <small id="surnameHelp" class="form-text text-muted">Podaj nazwiso osoby, która zarządza gospodarstwem.</small>
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ArimrNumber" class="control-label"></label>
                    <input asp-for="ArimrNumber" class="form-control" />
                    <span asp-validation-for="ArimrNumber" class="text-danger"></span>
                    <small id="arimrNumberHelp" class="form-text text-muted">Podaj numer otrzymany od ARIMR. (opcjonalnie) </small>
                </div>
                <div class="form-group">
                    <input type="submit" value="Zapisz" class="btn btn-primary" />
                    @Html.ActionLink("Powrót", "Index", new { }, new { @class = "btn btn-info" })
                    <button id="deleteBtn" class="btn btn-danger" onclick="deleteRow('@Model.Id')">Skasuj</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!--- End content -->


@section Scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/5.4.0/bootbox.min.js"></script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        function deleteRow(ID) {
        event.preventDefault();
        var url = '@Url.Action("Delete", "Operators", new { id = "Identifier" })';
        url = url.replace("Identifier", ID);

        bootbox.confirm({
            title: "Potwierdzenie",
            centerVertical: true,
            message: "Czy na pewno chcesz usunąć? Nie można cofnąć tej akcji.",
            buttons: {
                confirm: {
                    label: 'Usuń',
                    className: 'btn-success'
                },
                cancel: {
                    label: 'Anuluj',
                    className: 'btn-danger'
                }
            },
            callback: function(result) {
                if (result == true) {
                    {
                        window.location.replace(url);
                    }
                }
            }
        });
    }
    </script>
}

AgroSup.WebApp/Views/Operators/Index.cshtml
@model IEnumerable<AgroSup.WebApp.ViewModels.Operators.OperatorViewModel>

@{
    ViewData["Title"] = "Osoby";
    ViewData["Header"] = "Osoba prowadząca gospodarstwo zarejestrowane w systemie ARiMR";
    ViewData["ActivePage"] = ManageMenu.OperatorList;
    var message = @TempData["message"];
    int counter = 0;
}

<!--- Content -->
<div class="row">
    <partial name="_DataMenuPartial" />
    <div class="col-md-10">
        <div class="container-md mx-4">
            <p class="text-center" id="headerTitle">@ViewData["Header"]</p>
            <hr />
            @if (message != null)
            {
                <partial name="_StatusMessage" model="message.ToString()" />
            }
            <div class="table-responsive">
                <table id="axs" class="text-center table w-75 mx-auto table-striped table-hover">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">@Html.DisplayNameFor(modelItem => modelItem.FirstName)</th>
                            <th scope="col">@Html.DisplayNameFor(modelItem => modelItem.LastName)</th>
                            <th scope="col">@Html.DisplayNameFor(modelItem => modelItem.ArimrNumber)</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.Count() == 0)
                        {
                            <tr>
                                <td colspan="5">
                                    @Html.ActionLink("Dodaj osobę", "create", "operators", new { }, new { @class = "btn btn-info" })
                                </td>
                            </tr>
                        }
                        @foreach (var item in Model)
                        {
                            <tr>
                                <th class="align-middle" scope="row">@(++counter)</th>
                                <td class="align-middle">@Html.DisplayFor(modelItem => item.FirstName)</td>
                                <td class="align-middle">@Html.DisplayFor(modelItem => item.LastName)</td>
                                <td class="align-middle">@Html.DisplayFor(modelItem => item.ArimrNumber)</td>
                                <td class="align-middle">@Html.ActionLink("Edytuj", "Edit", new { id = item.Id }, new { @class = "btn btn-block btn btn-blue-grey" }) </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    </div>
    <!--- End content -->