AgroSup.WebApp/Controllers/AdminInActiveAccountsController.cs
using AgroSup.Core.Repositories;
using AgroSup.WebApp.ViewModels.AdminPanel.InActiveAccounts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace AgroSup.WebApp.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AdminInActiveAccountsController : Controller
    {
        private readonly IUserRepository _userRepository;

        public AdminInActiveAccountsController(IUserRepository userRepository)
        {
            _userRepository = userRepository;
        }
        public async Task<IActionResult> Index()
        {
            var AllUsers = await _userRepository.GetAll();
            var selectedUsersAmount = AgroSup.Core.Domain.User.GetInActiveUsers(AllUsers).Count();

            var model = new InActiveAccountViewModel()
            {
                PossibleAccountToDelete = selectedUsersAmount
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteAccounts()
        {
            var AllUsers = await _userRepository.GetAll();
            var SelectedUsers = AgroSup.Core.Domain.User.GetInActiveUsers(AllUsers);
            await _userRepository.Delete(SelectedUsers);
            TempData["message"] = "Konta zostały usunięte!";
            return RedirectToAction("Index");
        }
    }
}

AgroSup.WebApp/Views/AdminInActiveAccounts/Index.cshtml
@model AgroSup.WebApp.ViewModels.AdminPanel.InActiveAccounts.InActiveAccountViewModel

@{
    ViewData["Title"] = "Nieaktywne konta";
    ViewData["Header"] = "Usuń nieaktywne konta";
    ViewData["ActivePage"] = ManageMenu.InActiveAccounts;
    var message = @TempData["message"];
}

<div class="row">
    <partial name="_AdminMenuPartial" />
    <div class="col-md-10">
        <div class="container-md mx-4">
            <!--- Content -->
            <p class="text-center" id="headerTitle">@ViewData["Header"]</p>
            <hr />
            @if (message != null)
            {
                <partial name="_StatusMessage" model="message.ToString()" />
            }

            <pre>
            Konta przeznaczone do kasacji to te, które spełniają warunki:
            * Po utworzeniu nikt się nie zalogował przez conajmniej 90 dni.
            * Nie mają utworzonych żadnych planów oraz ostatni nikt się nie zalogował przez conajmniej 90 dni.
            Do usunięcia możliwych jest <strong>@Model.PossibleAccountToDelete</strong> kont
            <button id="deleteBtn" class="btn btn-danger">Skasuj</button>
</pre>
            <!--- End content -->
        </div>
        <form asp-action="DeleteAccounts" asp-controller="AdminInActiveAccounts" id="form">

        </form>
    </div>
</div>

@section Scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/5.4.0/bootbox.min.js"></script>
    <script>

        var konta = @Model.PossibleAccountToDelete;

        $('#deleteBtn').click(function () {
            var messageText = '<p>Czy jesteś pewien, że chcesz usunąć <strong>'+konta+'</strong> kont.</p>';
            messageText += '<p>Tej decyzji nie można cofnąć</p>';

            bootbox.confirm({
                buttons: {
                    confirm: {
                        label: 'Potwierdzam',
                        className: 'btn-success'
                    },
                    cancel: {
                        label: 'Anuluj',
                        className: 'btn-danger'
                    }
                },
                centerVertical: true,
                message: messageText,
                callback: function (result) {
                    if (result === true) {
                        $('#form').submit();
                    }
                }})
        })
    </script>
}